ALTER TABLE player_media ADD COLUMN IF NOT EXISTS scheduled_live_at TIMESTAMPTZ;
ALTER TABLE player_media ADD COLUMN IF NOT EXISTS is_live BOOLEAN DEFAULT FALSE;
ALTER TABLE player_media ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE player_media ADD COLUMN IF NOT EXISTS storage_path TEXT;
ALTER TABLE player_media ADD COLUMN IF NOT EXISTS source_type TEXT DEFAULT 'upload';
